name: Deploy .NET API to Azure Container Apps

on:
  push:
    branches: [ main ]

concurrency:
  group: single-run
  cancel-in-progress: false

env:
  AZURE_CONTAINER_REGISTRY: davidpaarup.azurecr.io 
  AZURE_CONTAINER_APP: ai-prompt-api
  AZURE_RESOURCE_GROUP: ai-prompt
  IMAGE_NAME: ai-prompt-api    
  PROJECT_NAME: AiPromptApi               

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Azure Container Registry
      run: |
        az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest --build-arg PROJECT_NAME=${{ env.PROJECT_NAME }} .
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Deploy to Azure Container Apps
      run: |
        az containerapp update \
          --name ${{ env.AZURE_CONTAINER_APP }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --image ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
 
